apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
  labels:
    app: {{ .Values.appLabel }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ .Values.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.appLabel }}
    spec:
      containers:
        - name: {{ .Values.deploymentName }}
          image: tomcat/8.0
          volumeMounts:
            - name: {{ .Values.volumeName }}
              mountPath: /usr/local/tomcat/webapps
          env:
            - name: TOMCAT_OPTS
              value: "--prefix=/tomcat"
          securityContext:
            fsGroup: 1000 
            runAsUser: 0
      volumes:
        - name: {{ .Values.volumeName }}
          persistentVolumeClaim:
            claimName: {{ .Values.claimName }}