apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deploymentName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.appLabel }}
  ports:
    - name: podport
      protocol: TCP
      port: 8085
      targetPort: 8080