apiVersion: v1
kind: Service
metadata:
  name: jenkins-alb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    alb.ingress.kubernetes.io/target-type: "instance"
spec:
  type: LoadBalancer
  selector:
    app: jenkins
  ports:
    - name: podport
      protocol: TCP
      port: 8080
      targetPort: 8080
