apiVersion: v1
kind: Service
metadata:
  name: jenkinssvc-nlb
spec:
  type: LoadBalancer
  selector:
    app: jenkins
  ports:
    - name: podport
      protocol: TCP
      port: 8080
      targetPort: 8080
