apiVersion: v1
kind: Pod
metadata:
  name: default-cpu
  namespace: example
spec:
  containers:
  - name: my-jenkins
    image: jenkins/jenkins
    resources:
      limits:
        cpu: "0.5"

        
#when we are not mentioning request it treats limit=request
        
