apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: example
spec:
  containers:
  - name: my-jenkin
    image: jenkins/jenkins
    resources:                                          
      requests:
        memory: "2Gi"
        cpu: "1"
      limits:
        memory: "4Gi"
        cpu: "2"
