apiVersion: v1
kind: Pod
metadata:
  name: default-cpu
  namespace: example
spec:
  containers:
  - name: my-jenkins
    image: jenkins/jenkins
    resources:
      requests:
        cpu: "0.5"

#default limits we get, when we are not mentioning limits and requesting for itrequestcpu.yml
