apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-varun
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: varun
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
